
import type { Metadata } from "next";
import "./globals.css";
import { ThemeContextProvider } from "@/styles/ThemeContext";
import { Providers } from "./providers";
import { LocalizationWrapper } from "@/components/LocalizationWrapper";

export const metadata: Metadata = {
  title: "Forms",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="es">
      <body>
        <Providers>
            <ThemeContextProvider>
              <LocalizationWrapper >
                {children}
              </LocalizationWrapper>
            </ThemeContextProvider>
        </Providers>
      </body>
    </html>
  );
}
